### ISSUE TITLE
Haier Air Conndition AS35S2SF2FA

### ISSUE THREAD

**Issue by algermi** [instalator/ioBroker.haier#14]
hi, 
i use a Haier Air Condition with built-in WIFI Module.
can i also use this adapter to connect it with IoBroker?
if i install the adapter and config the ip and ports will get the following error code:

Haier Error: read ECONNRESET

or is there another adapter?

https://klimacentar.com/proizvodi/multi-klima-uredaji/haier-multi-klima/brezza-green-as35s2sf2fa-851/

**Comment by instalator** [comment]
No, only esp8266
