### ISSUE TITLE
求美的中央空调网关ccm15适配器

### ISSUE THREAD

**Issue by lighu36** [instalator/ioBroker.haier#17]
能不能根据haier适配器改一下  让ccm15也能用

**Comment by instalator** [comment]
> 能不能根据haier适配器改一下 让ccm15也能用

haier does not have 485 tires.  I don’t understand what is required.

**Comment by lighu36** [comment]
> > 能不能根据haier适配器改一下让ccm15也能用
> 
> 海尔没有RS485数据总线。我不明白需要什么。
能否根据海尔的适配器  改一下    让美的的适配器ccm15也能接入iobroker
https://cac.midea.com/product/Control-Device/Network-Control/CCM15
![image](https://user-images.githubusercontent.com/44598569/70970997-dbc06580-20da-11ea-868e-f5692c1bd018.png)

**Comment by instalator** [comment]
This is not easy to do in the absence of equipment.
