### ISSUE TITLE
Packet length error

### ISSUE THREAD

**Issue by Kev0123** [instalator/ioBroker.haier#22]
I tried to use an Wemos D1 with a logic shifter and this is what I get as an result. Seem to be a wrong seperation of the raw string.
How to fix this?

![105497186-cf83e000-5cbe-11eb-98d4-bb5f7c5fa511](https://user-images.githubusercontent.com/19821853/105497604-5e90f800-5cbf-11eb-8b59-0f0e7242d45f.png)

Regards
Kevin

**Comment by Kev0123** [comment]
Managed to get the states to work by increasing the delay on the ESP side. Now I only get:
![image](https://user-images.githubusercontent.com/19821853/105577222-6e204780-5d78-11eb-8634-0de06d780e00.png)
How to filter them out?

**Comment by instalator** [comment]
You just need to adjust the code to fit your needs.
For example:
```
if (Serial.available()) {
    //size_t len = Serial.available();
    uint8_t sbuf[37];
    Serial.readBytes(sbuf, 37);
    //push UART data to all connected telnet clients
    for (i = 0; i < MAX_SRV_CLIENTS; i++) {
      if (clients[i] && clients[i].connected()) {
        clients[i].write(sbuf, 37);
        delay(1);
      }
    }
  }
```
OR
```
  uint8_t sbuf[100];
  uint8_t len = 0;
  if(Serial.available() > 0){
    len = 0;
    while (Serial.available() > 0) {
      sbuf[len] = (byte)Serial.read();
      len++;
      delay(5);
    }
    //push UART data to all connected telnet clients
    for(i = 0; i < MAX_SRV_CLIENTS; i++){
      if (clients[i] && clients[i].connected()){
        clients[i].write(sbuf, len);
        delay(1);
      }
    }
  }
```

**Comment by Kev0123** [comment]
Thank you very much! Solved my issue!
